//sample data not corosponding to reality in any form

var data=[
    {
        fname:"Mohan",
        lname:"Kumar",
        roll:"45",
        checkin:"10:10",
        checkout:"NA"
    },
    {
        fname:"Sonu",
        lname:"yadav",
        roll:"13",
        checkin:"10:00",
        checkout:"15:00"
    },
    {
        fname:"Ram",
        lname:"chandra",
        roll:"78",
        checkin:"10:20",
        checkout:"16:00"
    },
    {
        fname:"Soham",
        lname:"kumar",
        roll:"21",
        checkin:"8:00",
        checkout:"NA"
    },
    {
        fname:"Monu",
        lname:"agarwal",
        roll:"20",
        checkin:"8:01",
        checkout:"NA"
    },
    {
        fname:"Naruto",
        lname:"uzumaki",
        roll:"12",
        checkin:"12:00",
        checkout:"12:01"
    },
    {
        fname:"Manish",
        lname:"kumar",
        roll:"25",
        checkin:"10:58",
        checkout:"NA"
    },
    {
        fname:"Urvashi",
        lname:"Kumari",
        roll:"30",
        checkin:"10:59",
        checkout:"NA"
    },
    {
        fname:"Shilpy",
        lname:"agarwal",
        roll:"36",
        checkin:"10:10",
        checkout:"NA"
    },
    {
        fname:"Raju",
        lname:"ram",
        roll:"10",
        checkin:"10:11",
        checkout:"NA"
    },
    {
        fname:"Lalu",
        lname:"ram",
        roll:"11",
        checkin:"10:12",
        checkout:"NA"
    },
    {
        fname:"Monu",
        lname:"ram",
        roll:"9",
        checkin:"10:13",
        checkout:"NA"
    },
    {
        fname:"pragya",
        lname:"kumari",
        roll:"8",
        checkin:"12:1",
        checkout:"13:1"
    },
    {
        fname:"Mohan",
        lname:"Bisht",
        roll:"39",
        checkin:"19:56",
        checkout:"20:45"
    },
    {
        fname:"Sakshi",
        lname:"kumari",
        roll:"55",
        checkin:"8:45",
        checkout:"15:45"
    }
]

export default data;