var data=[
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"oooo"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"-iidi-"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"oddkdkdk"
    }
]

export default data;