var data=[
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    },
    {
        fname:"test",
        lname:"test",
        roll:"test",
        checkin:"test",
        checkout:"--"
    }
]

export default data;